### ISSUE TITLE
Uncaught TypeError: Cannot read property 'children' of undefined at getChildrenFromProps

### ISSUE THREAD

**Issue by Chun-Yang** [react-component/animate#29]
ERROR:
```
Uncaught TypeError: Cannot read property 'children' of undefined
    at getChildrenFromProps (modules.js?hash=c3bb3b2…:122940)
    at new Animate (modules.js?hash=c3bb3b2…:122968)
    at modules.js?hash=c3bb3b2…:36983
    at measureLifeCyclePerf (modules.js?hash=c3bb3b2…:36764)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (modules.js?hash=c3bb3b2…:36982)
    at ReactCompositeComponentWrapper._constructComponent (modules.js?hash=c3bb3b2…:36968)
    at ReactCompositeComponentWrapper.mountComponent (modules.js?hash=c3bb3b2…:36876)
    at Object.mountComponent (modules.js?hash=c3bb3b2…:29710)
    at ReactDOMComponent.mountChildren (modules.js?hash=c3bb3b2…:36062)
    at ReactDOMComponent._createInitialChildren (modules.js?hash=c3bb3b2…:33263)
```

FIX:
https://github.com/react-component/animate/blob/master/src/Animate.js#L70
change `this.props` to `props`

**Comment by benjycui** [comment]
Yep, you are right. PR is welcomed.

And you had better provide a re-producible demo first, I am curious why we didn't re-produce this issue before.

**Comment by paranoidjk** [comment]
I don’t get it, in this case,  this.props should equal to props?

**Comment by benjycui** [comment]
```jsx
class Test extends React.Component {
  constructor(props) {
    super();
    console.log(props, this.props, props === this.props); // => Object {} undefined false
  }
  render() {
    return null;
  } 
}

ReactDOM.render(<Test />, mountNode);
```

**Comment by paranoidjk** [comment]
@benjycui You should use super(props)

**Comment by benjycui** [comment]
@paranoidjk yep, this is OK.

Maybe you should upgrade your React first @Chun-Yang

**Comment by paranoidjk** [comment]
https://github.com/facebook/react/blob/master/src/isomorphic/modern/class/ReactBaseClasses.js#L24

**Comment by AsceticBoy** [comment]
I have this issue in IE 10 , but IE 11 or chrome browser is OK
`uncaught at _callee3 
 at _callee6 
 at takeEvery(alertView/queryViews, sagaWithCatch) 
 at sagaWithCatch 
 Error: TypeError: 无法获取未定义或 null 引用的属性“children”
   at getChildrenFromProps (http://localhost:8000/index.js:35449:4)
   at Animate (http://localhost:8000/index.js:35476:6)
   at Anonymous function (http://localhost:8000/index.js:133462:12)
   at measureLifeCyclePerf (http://localhost:8000/index.js:133243:6)
   at ReactCompositeComponent._constructComponentWithoutOwner (http://localhost:8000/index.js:133461:10)
   at ReactCompositeComponent._constructComponent (http://localhost:8000/index.js:133447:10)
   at ReactCompositeComponent.mountComponent (http://localhost:8000/index.js:133355:6)
   at ReactReconciler.mountComponent (http://localhost:8000/index.js:43860:6)
   at ReactMultiChild.Mixin.mountChildren (http://localhost:8000/index.js:137878:12)
   at ReactDOMComponent.Mixin._createInitialChildren (http://localhost:8000/index.js:134890:10)
   at Anonymous function (http://localhost:8000/index.js:112098:`

**Comment by yesmeck** [comment]
Fixed in the master.

**Comment by chetankumarguptha** [comment]
render {
     return (
         <RoomContext.Provider value="hello">
               {this.probs.children}         
         </RoomContext.Provider>

**Comment by mikadobrain** [comment]
> {this.probs.children}

Replace the b with a p.
