### ISSUE TITLE
 Cannot find module 'css-animation'

### ISSUE THREAD

**Issue by meodemsao** [react-component/animate#61]
i have issues with ant-design 

```sh
Error: Cannot find module 'css-animation'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/bangvu/Desktop/Projects/wtt/wttcms-frontend/node_modules/rc-animate/lib/AnimateChild.js:35:21
```

**Comment by etiennecaldo** [comment]
Same issue here when executing jest tests on my react application

```
Cannot find module 'css-animation' from 'AnimateChild.js'

    However, Jest was able to find:
        './AnimateChild.js'
```

**Comment by meodemsao** [comment]
@etiennecaldo i have to use npm-shrinkwrap.json to fix package version, you can try
